### ISSUE TITLE
minor mistake in comments

### ISSUE THREAD

**Issue by Pimss** [williampiat3/GeneticAlgorithm#1]
In the function `creation_deap_classes(creator,weights)` of every ga algorithms, minor mistakes are present in comments:
"wa are summing the wvalues" should be changed to "we are summing the values"

**Comment by williampiat3** [comment]
Thank you, you are corret for the first part of the sentence: there is definitly a mistake in "wa" BUT "wvalues" means the weighted values not the values.

**Comment by Pimss** [comment]
Oh, thanks ! I am rather new in ga so I haven't figured that out.
cheers mate !
